// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.20.3
// source: proto/users.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "users";

export interface RegisterRequest {
  email: string;
  password: string;
  name: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface GetProfileRequest {
  userId: string;
}

export interface UserResponse {
  userId: string;
  email: string;
  name: string;
}

export interface LoginResponse {
  accessToken: string;
  user: UserResponse | undefined;
}

export const USERS_PACKAGE_NAME = "users";

export interface UserServiceClient {
  register(request: RegisterRequest): Observable<UserResponse>;

  login(request: LoginRequest): Observable<LoginResponse>;

  getProfile(request: GetProfileRequest): Observable<UserResponse>;
}

export interface UserServiceController {
  register(request: RegisterRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  login(request: LoginRequest): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  getProfile(request: GetProfileRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["register", "login", "getProfile"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
